In [13]:
# strings

In [14]:
print("hello world")

hello world


In [36]:
var = "Hello This is Teja"

In [22]:
var[1:4]

'ell'

In [28]:
var.index("Teja")

14

In [37]:
var = var[:-4]
var

'Hello This is '

In [39]:
name = "Teja"
data = var+name

In [64]:
print("reverse string :",data[::-1])

reverse string : ajeT si sihT olleH


In [96]:
data=data.lower()

if var[::-1]+name[::-1] == data[::-1]:
    print("this is true")
else:
    print("this is false")

this is false


In [106]:
data[:10:2] # this means it will gives every 2nd string till index 10.

'hloti'

In [117]:
str_multiply = data[0:6]*3
str_multiply

'hello hello hello '

In [133]:
print('hello \t world') # tab 
print("hello \nworld")# new line
print("hello \\ world") # \
print(r"hello \ world") # read


hello 	 world
hello 
world
hello \ world
hello \ world


In [144]:
print(data)
print('index:',data.find('hello')) # hello index start at o . 

hello this is teja
index: 0


In [138]:
data

'hello this is teja'

In [153]:
str_replace = data.replace('hello','Hello') # string replacing.
str_replace

'Hello this is teja'

In [154]:
numbers = '0123456789'

numbers[::2]

'02468'

In [156]:
'0123'.find('1')

1

In [157]:
3+2*2

7

In [158]:
n = 'lizz'
n[0:2]

'li'

In [159]:
'1'+'2'

'12'

In [160]:
# lists and Tuples : 

#Tupples: 

In [174]:
tuple1 = ("teja",22)
print(type(tuple1))
tuple1

<class 'tuple'>


('teja', 22)

In [176]:
tuple2 = ('anil',23)
tuple2



('anil', 23)

In [183]:
tuple3  = tuple1+tuple2 # adding multiple tuples.
tuple3

('teja', 22, 'anil', 23)

In [229]:
tuple3[::-1]

(23, 'anil', 22, 'teja')

In [189]:
tuple4 = ('new',tuple3,'india')
tuple4

('new', ('teja', 22, 'anil', 23), 'india')

In [211]:
print(tuple4[0])
print(tuple4[1])
print(tuple4[2])

new
('teja', 22, 'anil', 23)
india


In [209]:
for i in tuple4[1]:
    if i == 22 or i == 23:
        print(i)

22
23


In [221]:
## lists: 

list1 = ['i',12,True,'indian']
print(list1[1])
list1


12


['i', 12, True, 'indian']

In [226]:
print(list1[0:2])
print(list[::-1])

['i', 12]
['indian', True, 12, 'i']


In [236]:

list1[4:5]=102,104 # append values.
list1

['i', 12, True, 'indian', 102, 104, 104]

In [240]:
list2 = [10,20,30,40]
list2

[10, 20, 30, 40]

In [242]:
# adding two lists : 
list3 = list1+list2
list3

['i', 12, True, 'indian', 102, 104, 10, 20, 30, 40]

In [247]:
list3

['i', 12, True, 'indian', 102, 104, 10, 20, 30, 40]

In [248]:
list3.append('value')
list3.extend(['value1','value2'])

In [249]:
list3

['i',
 12,
 True,
 'indian',
 102,
 104,
 10,
 20,
 30,
 40,
 'value',
 'value1',
 'value2']

In [251]:
del(list3[-3]) # removing values from the list.

In [252]:
list3

['i', 12, True, 'indian', 102, 104, 10, 20, 30, 40, 'value1', 'value2']

In [263]:
'hello this is teja jupyter notebook'.split()

['hello', 'this', 'is', 'teja', 'jupyter', 'notebook']

In [264]:
list3 

['i', 12, True, 'indian', 102, 104, 10, 20, 30, 40, 'value1', 'value2']

In [267]:
list4

['i', 12, True, 'indian', 102, 104, 10, 20, 30, 40, 'value1', 'value2']

In [272]:
list4[1]= 100

In [275]:
# we can get the copy of the data.

list5 = list4[:]

In [280]:
list4

['I', 100, True, 'indian', 102, 104, 10, 20, 30, 40, 'value1', 'value2']

In [283]:
len(tuple3)

4

In [287]:
#sets:
# sets having unique values.
# example : set = {1,2,3,4,5}
#type casting;


In [290]:
list3

['I', 100, True, 'indian', 102, 104, 10, 20, 30, 40, 'value1', 'value1']

In [293]:
# we can convert the data from list to set , this process called as type-casting;
set(list3)

{10, 100, 102, 104, 20, 30, 40, 'I', True, 'indian', 'value1'}

In [7]:
# it is only represent only unique values.
# we can insert ntypes of data types.
# it gives ascending order values.
set1 = {'hello','this','is','teja','teja','ballem'}
set1

{'ballem', 'hello', 'is', 'teja', 'this'}

In [309]:
'teja' in set1

True

In [310]:
# union and intersection.

set2 = {'hello','added','new_set'}

set1.union(set2)

{100, 'added', 'ballem', 'hello', 'is', 'new_set', 'teja', 'this'}

In [312]:
set1.intersection(set2)

{'hello'}

In [313]:
set1.remove(100)

In [315]:
A = [1, 2, 2, 1]
B = set([1, 2, 2, 1])

sum(A) == sum(B)

False

In [317]:
# we can add , remove 

3


In [319]:
## Dictionaries.

dict = {'col_1': 101, 'col_2':102,'col_3':103}
dict

{'col_1': 101, 'col_2': 102, 'col_3': 103}

In [323]:
print(dict.keys())
print(dict.values())

dict_keys(['col_1', 'col_2', 'col_3'])
dict_values([101, 102, 103])


In [337]:
'col_ 1' in dict

False

In [340]:
dict2 ={'col_1':(1,2,3,4,5),'col_2':(6,7,8,9,10)}
dict2

{'col_1': (1, 2, 3, 4, 5), 'col_2': (6, 7, 8, 9, 10)}

In [2]:
Dict={"A":1,"B":"2","C":[3,3,3],"D":(4,4,4),'E':5,'F':6}

Dict["D"]

(4, 4, 4)

In [5]:
x='a'

if(x!='a'):
    print("This is not a.")

else:
    print("This is a.")

This is a.


In [ ]:
## conditional statements:
# conditions and branching:---

# Operators :
    #(s +-*/ and or not in == !=) 

# if (condition):
    #statement
#elif(condition):
    #statement
#else:
    #statement


In [ ]:
## loops;

# for loop :

# while loop; 

In [11]:
for i in set1:
    print(i)

this
hello
is
ballem
teja


In [19]:
list_a = ['a','b','c','d']
list_b = ['e','f','g','h']

In [23]:
for i, j in enumerate(list_a):
    print(i)
    print(j)

0
a
1
b
2
c
3
d


In [31]:
# i = 0
#while (condition):
    #statement
    #i = i+1

# while loop: 
list_b = ['e','e','f','g','e']
new_list = []

i = 0

while (list_b[i]=='e'):
    new_list.append(list_b[i])
    i = i+1


In [32]:
new_list

[]

In [35]:
## functions:
def f(*x):
    return sum(x)

f(2,3)

5

In [36]:
A = ['1','2','3']

for a in A:
    print(2*a)

11
22
33


In [37]:
b= [2,1,4,3]

In [39]:
b.sort()
b

[1, 2, 3, 4]

In [40]:
import pandas as pd
df=pd.DataFrame({'a':[1,2,1],'b':[1,1,1]})

In [41]:
df['a']==1

0     True
1    False
2     True
Name: a, dtype: bool

In [42]:
import numpy as np



In [43]:
np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [44]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

In [45]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [47]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [48]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [49]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])